version: '3'
services:

  agent:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_URL=https://192.168.1.45:6443
    - K3S_TOKEN=K10b27af6f1f59ca88536e77f99560c85ac95261c6e59a9187f158d6c9478e5fc43::server:f7b5d6eab0aa000d7a8615065a40e40b
